// js/lang.js - Dictionary for Zynk i18n system

window.zynkTranslations = {
    vi: {
        // Common
        app_name: "Zynk",
        home: "Trang chủ",
        seller_center: "Kênh người bán",
        register_seller: "Đăng ký bán hàng",
        register_shop: "Đăng ký bán hàng",
        shop_active_title: "Cửa hàng của bạn đang hoạt động",
        shop_active_desc: "{name} — <a href='seller-center.html' style='color:#16a34a; font-weight:600;'>Vào Kênh Người Bán →</a>",
        pending_approval_title: "Đơn đăng ký đang chờ duyệt",
        pending_approval_desc: "Tên cửa hàng: <strong>{name}</strong>. Admin sẽ xem xét và phê duyệt trong thời gian sớm nhất.",
        rejected_approval_title: "Đơn đăng ký bị từ chối",
        rejected_approval_desc: "Đơn đăng ký <strong>{name}</strong> đã bị từ chối. Bạn có thể gửi lại đơn mới bên dưới.",
        seller_benefits_title: "Lợi ích khi trở thành người bán",
        seller_benefits_1: "Đăng bán sản phẩm đến hàng triệu người dùng",
        seller_benefits_2: "Quản lý đơn hàng và doanh thu trực quan",
        seller_benefits_3: "Tích hợp chat với khách hàng",
        seller_benefits_4: "Công cụ quản lý sản phẩm và kho hàng",
        shop_name_label: "Tên cửa hàng / Tên người bán",
        shop_name_placeholder: "Ví dụ: Cửa hàng của tôi",
        delivery_address_label: "Địa chỉ lấy/giao hàng mặc định",
        delivery_address_placeholder: "Nhập địa chỉ đầy đủ để người mua hoặc shipper dễ tìm kiếm...",
        auto_reply_label: "Tin nhắn trả lời tự động",
        auto_reply_desc: "Tự động gửi tin nhắn mẫu khi khách hàng bắt đầu chat.",
        auto_reply_placeholder: "Xin chào! Chúng tôi có thể giúp gì cho bạn?",
        marketplace_settings_desc: "Quản lý và thiết lập thông tin kinh doanh trên Marketplace.",
        register_seller_desc: "Đăng ký để mở cửa hàng và bắt đầu kinh doanh trên Zynk Marketplace.",
        save_marketplace_btn: "Lưu thiết lập Marketplace",
        send_application_btn: "Gửi đơn đăng ký",
        submitting: "Đang gửi...",
        register_success: "Đã gửi đơn đăng ký thành công! Admin sẽ xem xét sớm nhất.",
        register_failed: "Gửi đơn thất bại. Vui lòng thử lại.",
        marketplace: "Cửa hàng",
        my_orders: "Đơn mua",
        settings: "Cài đặt",
        profile: "Hồ sơ cá nhân",
        admin_panel: "Quản trị",
        logout: "Đăng xuất",
        login: "Đăng nhập",
        register: "Đăng ký",
        search_placeholder: "Tìm kiếm bài viết, người dùng...",
        loading: "Đang tải...",
        save_changes: "Lưu thay đổi",
        cancel: "Hủy",
        delete: "Xóa",
        user: "Người dùng",
        error: "Lỗi",
        
        // Header/Nav
        greeting: "Chào, ",
        notifications: "Thông báo",
        mark_all_read: "Đánh dấu tất cả đã đọc",
        no_notifications: "Không có thông báo mới",
        shopping: "Mua sắm",
        post_new: "Đăng bài mới",
        
        // Home Page
        news_feed: "Bảng tin",
        latest: "Mới nhất",
        following: "Đang theo dõi",
        discover: "Khám phá",
        suggested_for_you: "Gợi ý cho bạn",
        see_all: "Xem tất cả",
        view_profile: "Xem hồ sơ",
        no_posts: "Mọi thứ thật yên tĩnh. Hãy là người đầu tiên đăng bài!",
        quick_post_placeholder: "Bạn đang nghĩ gì thế?",
        
        // Report Modal
        report_post: "Báo cáo vi phạm",
        report_post_desc: "Chúng tôi sẽ xem xét bài viết này dựa trên lý do bạn cung cấp.",
        report_reason_not_like: "Tôi không thích nội dung này",
        report_reason_sensitive: "Vấn đề nhạy cảm/khiêu dâm",
        report_reason_violence: "Bạo lực",
        report_reason_political: "Phản động",
        report_reason_other: "Khác...",
        report_other_placeholder: "Vui lòng cung cấp thêm thông tin...",
        submit_report: "Gửi báo cáo",
        
        // Settings Page
        settings_title: "Cài đặt tài khoản",
        settings_desc: "Quản lý thông tin cá nhân và trải nghiệm của bạn.",
        tab_profile: "Hồ sơ cá nhân",
        tab_account: "Bảo mật",
        tab_privacy: "Quyền riêng tư",
        tab_notifications: "Thông báo",
        tab_marketplace: "Bán hàng",
        tab_interface: "Giao diện",
        tab_language: "Ngôn ngữ",
        tab_danger: "Vùng nguy hiểm",
        
        // --- Auth & Settings ---
        auth_title: "Xác thực - Zynk",
        auth_slogan: "Nền tảng mạng xã hội kết nối, chia sẻ kiến thức số 1.",
        auth_welcome: "Chào mừng trở lại!",
        email_placeholder: "Email của bạn",
        password_placeholder: "Mật khẩu",
        or_continue_with: "Hoặc tiếp tục với",
        back_to_home: "← Quay lại trang chủ",
        create_account: "Tạo tài khoản mới",
        fullname_placeholder: "Họ và Tên",
        select_gender: "Chọn giới tính",
        gender_male: "Nam",
        gender_female: "Nữ",
        gender_other: "Khác",
        password_req_placeholder: "Mật khẩu (Gồm chữ hoa, chữ thường và số)",
        confirm_password_placeholder: "Xác nhận mật khẩu",
        create_account_btn: "Tạo tài khoản",
        settings_profile_title: "Hồ sơ cá nhân",
        settings_profile_desc: "Cập nhật thông tin công khai của bạn trên Zynk.",
        username_label: "Tên người dùng (@username)",
        fullname_label: "Họ và tên",
        bio_label: "Tiểu sử",
        gender_label: "Giới tính",
        avatar_label: "Ảnh đại diện",
        change_btn: "Thay đổi",
        cover_label: "Ảnh bìa",
        change_cover_btn: "Thay đổi ảnh bìa",
        save_profile_btn: "Lưu hồ sơ",
        settings_account_title: "Bảo mật tài khoản",
        account_desc: "Quản lý mật khẩu và đăng nhập.",
        old_password_label: "Mật khẩu hiện tại",
        new_password_label: "Mật khẩu mới",
        confirm_password_label: "Xác nhận mật khẩu mới",
        change_password_btn: "Đổi mật khẩu",
        settings_privacy_title: "Quyền riêng tư",
        privacy_desc: "Kiểm soát ai có thể xem bài viết và tương tác với bạn.",
        private_account: "Tài khoản riêng tư",
        private_account_desc: "Bật chế độ này để ẩn bài viết của bạn với những người chưa theo dõi.",
        active_status: "Trạng thái hoạt động",
        active_status_desc: "Cho phép người khác thấy khi bạn đang online (dấu chấm xanh).",
        interaction_limits: "Giới hạn tương tác",
        who_can_message: "Ai có thể nhắn tin cho bạn?",
        everyone: "Mọi người",
        only_followers: "Chỉ người theo dõi",
        nobody: "Không ai",
        blocked_users: "Danh sách tài khoản đã chặn",
        blocked_users_desc: "Những người dùng bạn đã chặn sẽ không thể xem hồ sơ hoặc liên hệ với bạn.",
        settings_notifications_title: "Thông báo",
        notifications_desc: "Cấu hình cách bạn nhận thông báo từ hệ thống.",
        push_notification: "Thông báo đẩy (Web Push)",
        push_notification_desc: "Nhận thông báo trực tiếp trên web hoặc điện thoại.",
        email_notification: "Thông báo qua Email",
        email_notification_desc: "Nhận email thông báo hằng tuần.",
        marketplace_notification: "Thông báo đơn hàng Marketplace",
        marketplace_notification_desc: "Bao gồm tin nhắn mua hàng, thay đổi trạng thái đơn.",
        settings_interface_title: "Giao diện",
        interface_desc: "Cá nhân hóa trải nghiệm nhìn của bạn.",
        dark_mode: "Chế độ tối (Dark Mode)",
        dark_mode_desc: "Bật để giao diện trở nên dịu mắt hơn.",
        dark_mode_on: "Bật chế độ tối",
        dark_mode_off: "Tắt chế độ tối",
        settings_danger_title: "Vùng nguy hiểm",
        danger_desc: "Các hành động không thể hoàn tác.",
        delete_account: "Xóa tài khoản vĩnh viễn",
        delete_account_desc: "Lưu ý: Sau khi xóa, tất cả bài viết, ảnh và tương tác của bạn sẽ biến mất vĩnh viễn.",
        confirm_delete_account: "Xác nhận xóa tài khoản",
        
        // Language Section
        lang_section_title: "Ngôn ngữ hệ thống",
        lang_section_desc: "Chọn ngôn ngữ hiển thị bạn mong muốn.",
        select_lang: "Chọn ngôn ngữ",
        lang_vi: "Tiếng Việt",
        lang_en: "Tiếng Anh (English)",
        lang_ja: "Tiếng Nhật (日本語)",
        lang_applied: "Đã cập nhật ngôn ngữ!",
        
        // Profile Page
        posts_label: "Bài viết",
        followers_label: "Người theo dõi",
        following_label: "Đang theo dõi",
        friends_label: "Bạn bè",
        empty_list: "Danh sách trống.",
        follow: "Theo dõi",
        unfollow: "Hủy theo dõi",
        my_posts: "Bài đăng của tôi",
        no_posts_user: "Bạn chưa có bài đăng nào.",
        post_now: "Đăng bài ngay",
        create_post_title: "Tạo bài viết mới",
        post_title_label: "Tiêu đề",
        post_title_placeholder: "Nhập tiêu đề ấn tượng...",
        post_summary_label: "Tóm tắt (Ngắn gọn)",
        post_summary_placeholder: "Một vài dòng giới thiệu về bài viết...",
        post_images_label: "Hình ảnh bài viết (Có thể chọn nhiều)",
        post_images_btn: "Chọn ảnh bài viết",
        post_no_file: "Chưa có ảnh nào được chọn",
        post_content_label: "Nội dung",
        post_content_placeholder: "Bạn muốn chia sẻ điều gì với cộng đồng?",
        post_publish: "Đăng bài ngay",
        update_post_title: "Cập nhật bài viết",
        post_images_warning: "Lưu ý: Nếu bạn tải lên hình ảnh mới, toàn bộ hình ảnh cũ sẽ bị thay thế.",
        post_images_btn_edit: "Chọn ảnh mới tải lên",
        keep_old_images: "Giữ nguyên ảnh cũ",
        post_id_not_found: "Không tìm thấy ID bài viết!",
        load_post_failed: "Không tải được dữ liệu bài viết.",
        loaded_original_images: "Đã tải {count} ảnh ban đầu.",
        max_images_reached: "Chỉ được chọn tối đa 5 ảnh!",
        uploading_images: "Đang tải lên {count} ảnh...",
        upload_error: "Lỗi tải",
        upload_success_count: "Đã chọn và tải xong {count} ảnh mới.",
        update_success: "Cập nhật thành công!",
        default_bio: "Đây là nơi chia sẻ những suy nghĩ và câu chuyện của tôi.",
        user_timeline: "Dòng thời gian",
        users_section: "Người dùng",
        posts_section: "Bài viết",
        search_query_empty: "Vui lòng nhập từ khóa tìm kiếm",
        search_results_for: "Kết quả tìm kiếm cho:",
        no_users_found: "Không tìm thấy người dùng nào.",
        no_posts_found: "Không tìm thấy bài viết nào.",
        by_author: "Bởi",
        
        // Marketplace & Search
        search_btn: "Tìm",
        market_search_placeholder: "Tìm kiếm sản phẩm, cửa hàng...",
        categories_title: "Danh mục",
        all: "Tất cả",
        add_to_cart: "Thêm vào giỏ",
        buy_now: "Mua ngay",
        market_suggestions: "Gợi ý hôm nay",
        tag_shoes: "Giày",
        tag_shirts: "Áo",
        tag_bags: "Túi xách",
        price_low_high: "Giá thấp đến cao",
        price_high_low: "Giá cao đến thấp",
        best_seller: "Bán chạy",
        footer_desc: "Nền tảng chia sẻ & mua sắm.",
        
        // Cart & Orders
        cart_title: "Giỏ hàng của bạn",
        checkout: "Thanh toán",
        subtotal: "Tạm tính",
        total: "Tổng cộng",
        empty_cart: "Giỏ hàng trống",
        order_status: "Trạng thái đơn hàng",
        status_all: "Tất cả",
        status_pending: "Chờ xác nhận",
        status_unpaid: "Chưa thanh toán",
        status_awaiting: "Chờ giao hàng",
        status_delivering: "Đang giao",
        status_delivered: "Đã giao hàng",
        status_completed: "Hoàn thành",
        status_cancelled: "Đã hủy",
        orders_desc: "Theo dõi và quản lý lịch sử mua sắm của bạn",
        find_order: "Tìm đơn hàng",
        order_search_placeholder: "Tìm theo Mã đơn hoặc Tên sản phẩm...",
        searching: "Đang tìm kiếm...",
        
        // Order Details
        order_detail_title: "Chi tiết đơn hàng - Zynk",
        back_to_orders: "Quay lại đơn hàng mang tôi",
        shipping_address: "Địa chỉ nhận hàng",
        items_list: "Danh sách sản phẩm",
        order_summary: "Tổng kết đơn hàng",
        step_unpaid: "Chờ thanh toán",
        step_pending: "Chờ xác nhận",
        step_awaiting: "Chờ giao hàng",
        step_delivering: "Đang giao",
        step_completed: "Hoàn thành",
        payment_info_title: "Thanh toán",
        shipping_fee: "Phí vận chuyển",
        free: "Miễn phí",
        discount: "Giảm giá",
        total_payment: "Tổng thanh toán",
        order_info_title: "Thông tin đơn hàng",
        order_id_label: "Mã đơn hàng",
        order_time_label: "Thời gian đặt",
        payment_method_label: "Phương thức",
        
        // Seller Center Details
        seller_order_detail_title: "Chi tiết đơn hàng - Kênh Người Bán",
        back_to_seller_center: "Quay lại Kênh người bán",
        seller_loading_order: "Đang tải chi tiết đơn hàng cho người bán...",
        buyer_info: "Thông tin người mua",
        customer_name: "Tên khách hàng",
        phone_number: "Số điện thoại",
        pack_items: "Sản phẩm cần đóng gói",
        processing: "Xử lý đơn hàng",
        current_status: "Trạng thái hiện tại",
        auth_title: "Xác thực - Zynk",
        auth_welcome: "Chào mừng trở lại!",
        auth_slogan: "Nền tảng mạng xã hội kết nối, chia sẻ kiến thức số 1.",
        
        // Post Creation/Editing
        create_post_title: "Tạo bài viết mới",
        edit_post_title: "Chỉnh sửa bài viết",
        post_title_label: "Tiêu đề",
        post_title_placeholder: "Nhập tiêu đề ấn tượng...",
        post_summary_label: "Tóm tắt (Ngắn gọn)",
        post_summary_placeholder: "Một vài dòng giới thiệu về bài viết...",
        post_images_label: "Hình ảnh bài viết",
        post_images_btn: "Chọn ảnh bài viết",
        post_no_file: "Chưa có ảnh nào được chọn",
        post_content_label: "Nội dung bài viết",
        post_publish: "Đăng bài viết ngay",
        update_post_title: "Cập nhật bài viết",
        post_images_warning: "Lưu ý: Nếu bạn tải lên hình ảnh mới, toàn bộ hình ảnh cũ sẽ bị thay thế.",
        keep_old_images: "Giữ nguyên ảnh cũ",
        post_images_btn_edit: "Chọn ảnh mới tải lên",
        
        // Admin
        admin_dashboard: "Bảng điều khiển quản trị",
        manage_users: "Quản lý người dùng",
        manage_posts: "Quản lý bài viết",
        manage_shops: "Quản lý cửa hàng",
        system_stats: "Thống kê hệ thống",
        total_users: "Tổng người dùng",
        total_posts: "Tổng bài viết",
        total_orders: "Tổng đơn hàng",
        total_revenue: "Doanh thu hệ thống",
        violation_reports: "Báo cáo vi phạm",
        manage_categories: "Quản lý Danh mục",
        back_home: "Quay lại Home",
        users_list: "Danh sách người dùng",
        refresh: "Làm mới",

        // Seller Center
        open_shop_title: "Mở cửa hàng trên Zynk",
        open_shop_desc: "Bắt đầu sự nghiệp kinh doanh của bạn ngay hôm nay với cộng đồng Zynk.",
        shop_name_label: "Tên cửa hàng dự kiến",
        shop_name_placeholder: "Ví dụ: Zynk Mobile Store",
        shop_desc_label: "Mô tả shop",
        shop_desc_placeholder: "Giới thiệu ngắn về những gì bạn định bán...",
        submit_apply: "Gửi yêu cầu phê duyệt",
        seller_center_title: "Kênh Người Bán",
        shop_active_title: "Cửa hàng đang hoạt động",
        shop_rejected_title: "Đơn đăng ký bị từ chối",
        register_seller: "Đăng ký bán hàng",
        register_seller_desc: "Trở thành người bán trên Zynk để tiếp cận hàng ngàn khách hàng.",
        go_to_seller_center: "Truy cập Kênh Người Bán",
        overview: "Tổng quan",
        products: "Sản phẩm",
        orders: "Đơn hàng",
        revenue_est: "Doanh thu (Giả lập)",
        total_products: "Số lượng sản phẩm",
        product_list: "Danh sách sản phẩm",
        add_new_product: "Thêm sản phẩm mới",
        th_image: "Ảnh",
        th_name: "Tên sản phẩm",
        th_price: "Giá",
        th_stock: "Kho",
        th_status: "Trạng thái",
        th_actions: "Thao tác",
        manage_orders: "Quản lý đơn hàng",
        manage_orders_desc: "Quản lý và xử lý các đơn hàng của bạn",
        order_search_placeholder_full: "Tìm theo Mã đơn hàng, Tên hoặc SĐT khách hàng...",
        add_product_title: "Đăng sản phẩm mới",
        product_name_label: "Tên sản phẩm",
        product_price_label: "Giá bán (VND)",
        product_stock_label: "Số lượng kho",
        category_label: "Danh mục",
        product_desc_label: "Mô tả sản phẩm",
        upload_image: "Tải ảnh",
        variant_config: "Cấu hình Phân loại (Tùy chọn)",
        variant_group1_label: "Tên nhóm 1 (VD: Màu sắc)",
        variant_group2_label: "Tên nhóm 2 (VD: Dung lượng)",
        add_variant: "Thêm phân loại",
        save_and_show: "Lưu và Hiển thị",
        payment_settings_tab: "Thanh toán",
        payment_config_title: "Cấu hình Thanh toán VietQR",
        bank_name: "Ngân hàng",
        bank_account_number: "Số tài khoản",
        bank_account_name: "Tên chủ tài khoản (Không dấu)",
        save_payment_config: "Lưu cấu hình thanh toán",

        // Seller Order Detail
        back_to_seller_center: "Quay lại Kênh người bán",
        seller_loading_order: "Đang tải chi tiết đơn hàng cho người bán...",
        buyer_info: "Thông tin người mua",
        customer_name: "Tên khách hàng",
        phone_number: "Số điện thoại",
        pack_items: "Sản phẩm cần đóng gói",
        payment_info: "Thông tin thanh toán",
        total_amount: "Tổng tiền",
        payment_method: "Phương thức",
        order_processing: "Xử lý đơn hàng",
        current_status: "Trạng thái hiện tại:",
        order_id_label: "Mã đơn hàng:",
        order_date_label: "Ngày đặt:",

        // Order Detail (Buyer)
        back_to_my_orders: "Quay lại đơn hàng của tôi",
        loading_order_info: "Đang tải thông tin đơn hàng...",
        order_success: "Đặt hàng thành công",
        preparing_items: "Đang chuẩn bị hàng",
        shipping_fee: "Phí vận chuyển",
        free: "Miễn phí",
        discount: "Giảm giá",
        total_payment: "Tổng thanh toán",
        order_info_title: "Thông tin đơn hàng",
        order_time_label: "Thời gian đặt",
        payment_method_label: "Phương thức",
        cancel_order: "Hủy đơn hàng",
        update_address_title: "Cập nhật địa chỉ giao hàng",
        province_label: "Tỉnh/Thành phố",
        dist_ward_label: "Quận/Huyện - Phường/Xã",
        specific_address_label: "Địa chỉ cụ thể",

        // Cart
        total_label: "Tổng cộng:",
        shipping_info_title: "Thông tin nhận hàng",
        saved_addresses: "Địa chỉ đã lưu",
        select_province: "Chọn Tỉnh/Thành",
        district_label: "Quận / Huyện",
        select_district: "Chọn Quận/Huyện",
        save_address_future: "Lưu thông tin địa chỉ này cho lần sau",
        order_note_optional: "Ghi chú đơn hàng (Tùy chọn)",
        payment_method_title: "Phương thức thanh toán",
        payment_cod: "Thanh toán khi nhận hàng (COD)",
        payment_bank: "Thẻ ngân hàng / Chuyển khoản",
        order_now: "Đặt hàng ngay",
        empty_cart: "Giỏ hàng trống.",
        processing: "Đang xử lý...",
        select_all: "Chọn tất cả",

        // Admin
        admin_dashboard: "Quản trị hệ thống",
        manage_users: "Quản lý Người dùng",
        violation_reports: "Báo cáo vi phạm",
        manage_shops: "Quản lý Cửa hàng",
        manage_categories: "Quản lý Danh mục",
        back_home: "Quay lại Home",
        users_list: "Danh sách người dùng",
        reporter: "Người báo cáo",
        reported_post: "Bài viết bị báo cáo",
        reason: "Lý do",
        status: "Trạng thái",
        applicant: "Người đăng ký",
        shop_name: "Tên Shop",
        request_date: "Ngày gửi",
        categories_desc_admin: "Bấm vào danh mục để xem các mục con bên trong",
        add_category: "Thêm Danh mục",
        category_name_label: "Tên danh mục",
        category_icon_label: "Icon (FontAwesome class)",
        parent_category_label: "Danh mục cha",
        none_root: "-- Không có (Danh mục gốc) --",
        preview_post_title: "Xem trước bài viết",
        
        // Footer
        footer_copy: "&copy; 2026 Zynk Community. Made with LV for developers."
    },
    en: {
        // Common
        app_name: "Zynk",
        home: "Home",
        marketplace: "Zynk Market",
        seller_center: "Seller Center",
        register_seller: "Register Seller",
        register_shop: "Register Shop",
        my_orders: "My Orders",
        settings: "Settings",
        profile: "Profile",
        admin_panel: "Admin",
        logout: "Logout",
        login: "Login",
        register: "Register",
        search_placeholder: "Search posts, users...",
        loading: "Loading...",
        save_changes: "Save Changes",
        cancel: "Cancel",
        delete: "Delete",
        user: "User",
        error: "Error",
        
        // Header/Nav
        greeting: "Hi, ",
        notifications: "Notifications",
        mark_all_read: "Mark all as read",
        no_notifications: "No new notifications",
        shopping: "Shopping",
        post_new: "Post New",
        
        // Home Page
        news_feed: "News Feed",
        latest: "Latest",
        following: "Following",
        discover: "Discover",
        suggested_for_you: "Suggested for you",
        see_all: "See all",
        view_profile: "View profile",
        no_posts: "Everything is quiet. Be the first to post!",
        quick_post_placeholder: "What's on your mind?",

        // Report Modal
        report_post: "Report Violation",
        report_post_desc: "We will review this post based on the reason you provide.",
        report_reason_not_like: "I don't like this content",
        report_reason_sensitive: "Sensitive/Adult content",
        report_reason_violence: "Violence",
        report_reason_political: "Political/Rebellion",
        report_reason_other: "Other...",
        report_other_placeholder: "Please provide more information...",
        submit_report: "Submit Report",
        
        // Settings Page
        settings_title: "Account Settings",
        settings_desc: "Manage your personal information and experience.",
        tab_profile: "Profile",
        tab_account: "Security",
        tab_privacy: "Privacy",
        tab_notifications: "Notifications",
        seller_center: "Seller Center",
        register_seller: "Become a Seller",
        shop_active_title: "Your shop is active",
        shop_active_desc: "{name} — <a href='seller-center.html' style='color:#16a34a; font-weight:600;'>Go to Seller Center →</a>",
        pending_approval_title: "Application pending approval",
        pending_approval_desc: "Shop name: <strong>{name}</strong>. Admin will review and approve shortly.",
        rejected_approval_title: "Application rejected",
        rejected_approval_desc: "Application for <strong>{name}</strong> was rejected. You can resubmit below.",
        seller_benefits_title: "Benefits of becoming a seller",
        seller_benefits_1: "Sell products to millions of users",
        seller_benefits_2: "Intuitive order and revenue management",
        seller_benefits_3: "Integrated chat with customers",
        seller_benefits_4: "Product and inventory management tools",
        shop_name_label: "Shop Name / Seller Name",
        shop_name_placeholder: "Example: My Awesome Shop",
        delivery_address_label: "Default pickup/delivery address",
        delivery_address_placeholder: "Enter full address for buyers or shippers to find easily...",
        auto_reply_label: "Auto-reply message",
        auto_reply_desc: "Automatically send a template message when customers start a chat.",
        auto_reply_placeholder: "Hello! How can we help you today?",
        marketplace_settings_desc: "Manage and set up business information on Marketplace.",
        register_seller_desc: "Register to open a shop and start business on Zynk Marketplace.",
        save_marketplace_btn: "Save Marketplace Settings",
        send_application_btn: "Submit Application",
        submitting: "Submitting...",
        register_success: "Application submitted successfully! Admin will review it soon.",
        register_failed: "Submission failed. Please try again.",
        marketplace: "Marketplace",
        tab_interface: "Appearance",
        tab_language: "Language",
        tab_danger: "Danger Zone",
        
        // --- Auth & Settings ---
        auth_title: "Authentication - Zynk",
        auth_slogan: "The #1 social network for knowledge sharing.",
        auth_welcome: "Welcome back!",
        email_placeholder: "Your Email",
        password_placeholder: "Password",
        or_continue_with: "Or continue with",
        back_to_home: "← Back to home",
        create_account: "Create new account",
        fullname_placeholder: "Full Name",
        select_gender: "Select gender",
        gender_male: "Male",
        gender_female: "Female",
        gender_other: "Other",
        password_req_placeholder: "Password (Upper, lower & numbers)",
        confirm_password_placeholder: "Confirm password",
        create_account_btn: "Create account",
        settings_profile_title: "Profile",
        settings_profile_desc: "Update your public information on Zynk.",
        username_label: "Username (@username)",
        fullname_label: "Full Name",
        bio_label: "Bio",
        gender_label: "Gender",
        avatar_label: "Avatar",
        change_btn: "Change",
        cover_label: "Cover Image",
        change_cover_btn: "Change cover",
        save_profile_btn: "Save profile",
        settings_account_title: "Account Security",
        account_desc: "Manage password and login.",
        old_password_label: "Current Password",
        new_password_label: "New Password",
        confirm_password_label: "Confirm New Password",
        change_password_btn: "Change Password",
        settings_privacy_title: "Privacy",
        privacy_desc: "Control who can see your posts and interact with you.",
        private_account: "Private Account",
        private_account_desc: "Enable this to hide your posts from people who don't follow you.",
        active_status: "Active Status",
        active_status_desc: "Let others see when you are online (green dot).",
        interaction_limits: "Interaction Limits",
        who_can_message: "Who can message you?",
        everyone: "Everyone",
        only_followers: "Only Followers",
        nobody: "Nobody",
        blocked_users: "Blocked Users List",
        blocked_users_desc: "Users you have blocked cannot see your profile or contact you.",
        settings_notifications_title: "Notifications",
        notifications_desc: "Configure how you receive system notifications.",
        push_notification: "Web Push Notifications",
        push_notification_desc: "Receive notifications directly on web or phone.",
        email_notification: "Email Notifications",
        email_notification_desc: "Receive weekly email notifications.",
        marketplace_notification: "Marketplace Order Notifications",
        marketplace_notification_desc: "Includes purchase messages, order status changes.",
        settings_interface_title: "Appearance",
        interface_desc: "Personalize your visual experience.",
        dark_mode: "Dark Mode",
        dark_mode_desc: "Turn on to make the interface easier on the eyes.",
        dark_mode_on: "Turn on dark mode",
        dark_mode_off: "Turn off dark mode",
        settings_danger_title: "Danger Zone",
        danger_desc: "Irreversible actions.",
        delete_account: "Permanently Delete Account",
        delete_account_desc: "Note: Once deleted, all your posts, photos, and interactions will be gone forever.",
        confirm_delete_account: "Confirm Delete Account",

        // Language Section
        lang_section_title: "System Language",
        lang_section_desc: "Choose your preferred display language.",
        select_lang: "Select Language",
        lang_vi: "Vietnamese",
        lang_en: "English",
        lang_ja: "Japanese (日本語)",
        lang_applied: "Language updated!",

        // Profile Page
        posts_label: "Posts",
        followers_label: "Followers",
        following_label: "Following",
        friends_label: "Friends",
        empty_list: "List is empty.",
        follow: "Follow",
        unfollow: "Unfollow",
        my_posts: "My Posts",
        no_posts_user: "You don't have any posts yet.",
        post_now: "Post now",
        create_post_title: "Create New Post",
        post_title_label: "Title",
        post_title_placeholder: "Enter an impressive title...",
        post_summary_label: "Summary (Brief)",
        post_summary_placeholder: "A few introductory lines about the post...",
        post_images_label: "Post Images (Can select multiple)",
        post_images_btn: "Select post images",
        post_no_file: "No files selected yet",
        post_content_label: "Content",
        post_content_placeholder: "What do you want to share with the community?",
        post_publish: "Publish Now",
        update_post_title: "Update Post",
        post_images_warning: "Note: If you upload new images, all old images will be replaced.",
        post_images_btn_edit: "Select new images to upload",
        keep_old_images: "Keep old images",
        post_id_not_found: "Post ID not found!",
        load_post_failed: "Failed to load post data.",
        loaded_original_images: "Loaded {count} original images.",
        max_images_reached: "Maximum 5 images allowed!",
        uploading_images: "Uploading {count} images...",
        upload_error: "Upload error",
        upload_success_count: "Selected and uploaded {count} new images.",
        update_success: "Update successful!",
        default_bio: "This is where I share my thoughts and stories.",
        user_timeline: "User Timeline",
        users_section: "Users",
        posts_section: "Posts",
        search_query_empty: "Please enter a search keyword",
        search_results_for: "Search results for:",
        no_users_found: "No users found.",
        no_posts_found: "No posts found.",
        by_author: "By",

        // Marketplace & Search
        search_btn: "Search",
        market_search_placeholder: "Search products, shops...",
        categories_title: "Categories",
        all: "All",
        add_to_cart: "Add to Cart",
        buy_now: "Buy Now",
        market_suggestions: "Daily Suggestions",
        tag_shoes: "Shoes",
        tag_shirts: "Shirts",
        tag_bags: "Bags",
        price_low_high: "Price: Low to High",
        price_high_low: "Price: High to Low",
        best_seller: "Best Seller",
        footer_desc: "Sharing & Shopping Platform.",

        // Cart & Orders
        cart_title: "Your Cart",
        checkout: "Checkout",
        subtotal: "Subtotal",
        total: "Total",
        empty_cart: "Your cart is empty",
        order_status: "Order Status",
        status_all: "All",
        status_pending: "Pending",
        status_unpaid: "Unpaid",
        status_awaiting: "Awaiting Shipment",
        status_delivering: "Delivering",
        status_delivered: "Delivered",
        status_completed: "Completed",
        status_cancelled: "Cancelled",
        orders_desc: "Follow and manage your shopping history",
        find_order: "Find Order",
        order_search_placeholder: "Search by Order ID or Product name...",
        searching: "Searching...",
        
        // Order Details
        order_detail_title: "Order Detail - Zynk",
        back_to_orders: "Back to my orders",
        shipping_address: "Shipping Address",
        items_list: "Product List",
        order_summary: "Order Summary",
        step_unpaid: "Unpaid",
        step_pending: "Pending",
        step_awaiting: "Awaiting Shipment",
        step_delivering: "Delivering",
        step_completed: "Completed",
        payment_info_title: "Payment",
        shipping_fee: "Shipping Fee",
        free: "Free",
        discount: "Discount",
        total_payment: "Total Payment",
        order_info_title: "Order Information",
        order_id_label: "Order ID",
        order_time_label: "Order Time",
        payment_method_label: "Method",
        
        // Seller Center Details
        seller_order_detail_title: "Order Detail - Seller Center",
        back_to_seller_center: "Back to Seller Center",
        seller_loading_order: "Loading order details for seller...",
        buyer_info: "Buyer Information",
        customer_name: "Customer Name",
        phone_number: "Phone Number",
        pack_items: "Items to Pack",
        processing: "Processing",
        current_status: "Current Status",
        auth_title: "Auth - Zynk",
        auth_welcome: "Welcome Back!",
        auth_slogan: "Top social platform for knowledge sharing.",

        // Post Creation/Editing
        create_post_title: "Create New Post",
        edit_post_title: "Edit Post",
        post_title_label: "Title",
        post_title_placeholder: "Enter an impressive title...",
        post_summary_label: "Summary (Brief)",
        post_summary_placeholder: "A few lines of introduction...",
        post_images_label: "Post Images",
        post_images_btn: "Select images",
        post_no_file: "No images selected",
        post_content_label: "Post Content",
        post_publish: "Publish Post Now",
        update_post_title: "Update Post",
        post_images_warning: "Note: If you upload new images, all old ones will be replaced.",
        keep_old_images: "Keep old images",
        post_images_btn_edit: "Select new images to upload",

        // Admin
        admin_dashboard: "Admin Dashboard",
        manage_users: "Manage Users",
        manage_posts: "Manage Posts",
        manage_shops: "Manage Shops",
        system_stats: "System Statistics",
        total_users: "Total Users",
        total_posts: "Total Posts",
        total_orders: "Total Orders",
        total_revenue: "System Revenue",
        violation_reports: "Violation Reports",
        manage_categories: "Manage Categories",
        back_home: "Back to Home",
        users_list: "Users List",
        refresh: "Refresh",
        
        // Seller Center
        open_shop_title: "Open Shop on Zynk",
        open_shop_desc: "Start your business career today with the Zynk community.",
        shop_name_label: "Expected Shop Name",
        shop_name_placeholder: "Ex: Zynk Mobile Store",
        shop_desc_label: "Shop Description",
        shop_desc_placeholder: "Short introduction about what you plan to sell...",
        submit_apply: "Submit for Approval",
        pending_approval_title: "Profile Pending Approval",
        pending_approval_desc: "Admin is reviewing your shop application. We will notify you as soon as there is a result.",
        seller_center_title: "Seller Center",
        shop_active_title: "Shop is Active",
        shop_rejected_title: "Application Rejected",
        register_seller: "Register as Seller",
        register_seller_desc: "Become a seller on Zynk to reach thousands of customers.",
        go_to_seller_center: "Go to Seller Center",
        overview: "Overview",
        products: "Products",
        orders: "Orders",
        revenue_est: "Estimated Revenue",
        total_products: "Total Products",
        product_list: "Product List",
        add_new_product: "Add New Product",
        th_image: "Image",
        th_name: "Product Name",
        th_price: "Price",
        th_stock: "Stock",
        th_status: "Status",
        th_actions: "Actions",
        manage_orders: "Order Management",
        manage_orders_desc: "Manage and process your orders",
        order_search_placeholder_full: "Search by Order ID, Name, or Customer Phone...",
        add_product_title: "Add New Product",
        product_name_label: "Product Name",
        product_price_label: "Price (VND)",
        product_stock_label: "Stock Quantity",
        category_label: "Category",
        product_desc_label: "Product Description",
        upload_image: "Upload Image",
        variant_config: "Variant Configuration (Optional)",
        variant_group1_label: "Group 1 Name (Ex: Color)",
        variant_group2_label: "Group 2 Name (Ex: Size)",
        add_variant: "Add Variant",
        save_and_show: "Save and Publish",
        payment_settings_tab: "Payment",
        payment_config_title: "VietQR Payment Configuration",
        bank_name: "Bank",
        bank_account_number: "Account Number",
        bank_account_name: "Account Holder Name (No accents)",
        save_payment_config: "Save Payment Configuration",

        // Seller Order Detail
        back_to_seller_center: "Back to Seller Center",
        seller_loading_order: "Loading order details for seller...",
        buyer_info: "Buyer Information",
        customer_name: "Customer Name",
        phone_number: "Phone Number",
        pack_items: "Items to Pack",
        payment_info: "Payment Information",
        total_amount: "Total Amount",
        payment_method: "Payment Method",
        order_processing: "Order Processing",
        current_status: "Current Status:",
        order_id_label: "Order ID:",
        order_date_label: "Order Date:",

        // Order Detail (Buyer)
        back_to_my_orders: "Back to My Orders",
        loading_order_info: "Loading order information...",
        order_success: "Order Success",
        preparing_items: "Preparing Items",
        shipping_fee: "Shipping Fee",
        free: "Free",
        discount: "Discount",
        total_payment: "Total Payment",
        order_info_title: "Order Information",
        order_time_label: "Order Time",
        payment_method_label: "Payment Method",
        cancel_order: "Cancel Order",
        update_address_title: "Update Shipping Address",
        province_label: "Province/City",
        dist_ward_label: "District/Ward",
        specific_address_label: "Specific Address",

        // Cart
        total_label: "Total:",
        shipping_info_title: "Shipping Information",
        saved_addresses: "Saved Addresses",
        select_province: "Select Province/City",
        district_label: "District / Town",
        select_district: "Select District",
        save_address_future: "Save this address for next time",
        order_note_optional: "Order Note (Optional)",
        payment_method_title: "Payment Method",
        payment_cod: "Cash on Delivery (COD)",
        payment_bank: "Bank Transfer / Card",
        order_now: "Order Now",
        empty_cart: "Your cart is empty.",
        processing: "Processing...",
        select_all: "Select All",

        // Admin
        admin_dashboard: "Admin Dashboard",
        manage_users: "Manage Users",
        violation_reports: "Violation Reports",
        manage_shops: "Manage Shops",
        manage_categories: "Manage Categories",
        back_home: "Back to Home",
        users_list: "Users List",
        reporter: "Reporter",
        reported_post: "Reported Post",
        reason: "Reason",
        status: "Status",
        applicant: "Applicant",
        shop_name: "Shop Name",
        request_date: "Request Date",
        categories_desc_admin: "Click on a category to see its sub-items",
        add_category: "Add Category",
        category_name_label: "Category Name",
        category_icon_label: "Icon (FontAwesome class)",
        parent_category_label: "Parent Category",
        none_root: "-- None (Root Category) --",
        preview_post_title: "Preview Post",

        // Footer
        footer_copy: "&copy; 2026 Zynk Community. Made with LV for developers."
    },
    ja: {
        // Common (Japanese)
        app_name: "Zynk",
        home: "ホーム",
        seller_center: "セラーセンター",
        register_seller: "出店登録",
        register_shop: "ショップ登録",
        shopping: "ショッピング",
        shop_active_title: "あなたのショップは有効です",
        shop_active_desc: "{name} — <a href='seller-center.html' style='color:#16a34a; font-weight:600;'>セラーセンターへ移動 →</a>",
        pending_approval_title: "申請承認待ち",
        pending_approval_desc: "ショップ名: <strong>{name}</strong>。管理者がまもなく確認し、承認します。",
        rejected_approval_title: "申請が拒否されました",
        rejected_approval_desc: "<strong>{name}</strong> の申請は拒否されました。以下から再申請できます。",
        seller_benefits_title: "セラーになるメリット",
        seller_benefits_1: "数百万のユーザーに製品を販売",
        seller_benefits_2: "直感的な注文と収益の管理",
        seller_benefits_3: "顧客との統合チャット",
        seller_benefits_4: "製品および在庫管理ツール",
        shop_name_label: "ショップ名 / 出品者名",
        shop_name_placeholder: "例：マイショップ",
        delivery_address_label: "デフォルトの集荷/配送先住所",
        delivery_address_placeholder: "購入者や配送業者が簡単に見つけられるように、完全な住所を入力してください...",
        auto_reply_label: "自動返信メッセージ",
        auto_reply_desc: "顧客がチャットを開始したときにテンプレートメッセージを自動的に送信します。",
        auto_reply_placeholder: "こんにちは！本日はどのようなご用件でしょうか？",
        marketplace_settings_desc: "マーケットプレイスのビジネス情報を管理・設定します。",
        register_seller_desc: "出店登録をして、Zynkマーケットプレイスでビジネスを始めましょう。",
        save_marketplace_btn: "マーケットプレイス設定を保存",
        send_application_btn: "申請を送信",
        submitting: "送信中...",
        register_success: "申請が正常に送信されました！管理者がまもなく確認します。",
        register_failed: "送信に失敗しました。もう一度お試しください。",
        marketplace: "マーケットプレイス",
        my_orders: "購入注文",
        settings: "設定",
        profile: "プロファイル",
        admin_panel: "管理",
        logout: "ログアウト",
        login: "ログイン",
        register: "登録",
        search_placeholder: "検索する...",
        loading: "読み込み中...",
        save_changes: "保存する",
        cancel: "キャンセル",
        delete: "削除",
        user: "ユーザー",
        error: "エラー",
        
        // Header/Nav
        greeting: "こんにちは、",
        notifications: "通知",
        mark_all_read: "すべて既読にする",
        no_notifications: "通知はありません",
        shopping: "ショッピング",
        post_new: "投稿する",
        
        // Home Page
        news_feed: "フィード",
        latest: "最新",
        following: "フォロー中",
        no_posts: "まだ投稿がありません。",
        quick_post_placeholder: "何を考えていますか？",

        // Report Modal
        report_post: "違反を報告する",
        report_post_desc: "提供された理由に基づいて、この投稿を審査します。",
        report_reason_not_like: "このコンテンツが気に入らない",
        report_reason_sensitive: "機密/成人向けコンテンツ",
        report_reason_violence: "暴力",
        report_reason_political: "政治的/反逆的",
        report_reason_other: "その他...",
        report_other_placeholder: "詳細情報を入力してください...",
        submit_report: "報告を送信",
        
        // --- Auth & Settings ---
        auth_title: "認証 - Zynk",
        auth_slogan: "知識共有のためのNo.1ソーシャルネットワーク。",
        auth_welcome: "お帰りなさい！",
        email_placeholder: "メールアドレス",
        password_placeholder: "パスワード",
        or_continue_with: "または以下で続ける",
        back_to_home: "← ホームに戻る",
        create_account: "新しいアカウントを作成",
        fullname_placeholder: "氏名",
        select_gender: "性別を選択",
        gender_male: "男性",
        gender_female: "女性",
        gender_other: "その他",
        password_req_placeholder: "パスワード（大文字・小文字・数字）",
        confirm_password_placeholder: "パスワードを確認",
        create_account_btn: "アカウントを作成",
        settings_profile_title: "プロフィール",
        settings_profile_desc: "Zynkでの公開情報を更新します。",
        username_label: "ユーザーネーム (@username)",
        fullname_label: "氏名",
        bio_label: "自己紹介",
        gender_label: "性別",
        avatar_label: "アバター",
        change_btn: "変更",
        cover_label: "カバー画像",
        change_cover_btn: "カバーを変更",
        save_profile_btn: "プロフィールを保存",
        settings_account_title: "アカウントのセキュリティ",
        account_desc: "パスワードとログインを管理します。",
        old_password_label: "現在のパスワード",
        new_password_label: "新しいパスワード",
        confirm_password_label: "新しいパスワード（確認）",
        change_password_btn: "パスワードを変更",
        settings_privacy_title: "プライバシー",
        privacy_desc: "投稿の閲覧者やインタラクションを制御します。",
        private_account: "非公開アカウント",
        private_account_desc: "フォローしていない人から投稿を隠すには、これを有効にします。",
        active_status: "アクティビティのステータス",
        active_status_desc: "オンライン時（緑色のドット）を他のユーザーに表示します。",
        interaction_limits: "インタラクション制限",
        who_can_message: "誰があなたにメッセージを送れますか？",
        everyone: "全員",
        only_followers: "フォロワーのみ",
        nobody: "誰も送れない",
        blocked_users: "ブロックしたユーザーのリスト",
        blocked_users_desc: "ブロックしたユーザーは、あなたのプロフィールを閲覧したり、連絡したりできません。",
        settings_notifications_title: "通知",
        notifications_desc: "システム通知の受信方法を設定します。",
        push_notification: "Webプッシュ通知",
        push_notification_desc: "ウェブやスマートフォンで直接通知を受け取ります。",
        email_notification: "メール通知",
        email_notification_desc: "週次のメール通知を受け取ります。",
        marketplace_notification: "マーケットプレイスの注文通知",
        marketplace_notification_desc: "購入メッセージや注文状況の変更が含まれます。",
        settings_interface_title: "外観",
        interface_desc: "視覚的な体験をカスタマイズします。",
        dark_mode: "ダークモード",
        dark_mode_desc: "目に優しいインターフェースにするにはオンにします。",
        dark_mode_on: "ダークモードをオンにする",
        dark_mode_off: "ダークモードをオフにする",
        settings_danger_title: "危険なゾーン",
        danger_desc: "元に戻せないアクション。",
        delete_account: "アカウントを完全に削除する",
        delete_account_desc: "注：削除すると、すべての投稿、写真、インタラクションが永久に消去されます。",
        confirm_delete_account: "アカウント削除を確認する",

        // Language Section
        lang_section_title: "システム言語",
        lang_section_desc: "表示言語を選択してください。",
        select_lang: "言語を選択",
        lang_vi: "ベトナム語",
        lang_en: "英語",
        lang_ja: "日本語",
        lang_applied: "言語を更新しました！",

        // Profile Page
        posts_label: "投稿",
        followers_label: "フォロワー",
        following_label: "フォロー中",
        follow: "フォロー",
        unfollow: "フォロー解除",
        my_posts: "私の投稿",
        no_posts_user: "投稿はまだありません。",
        post_now: "今すぐ投稿",
        create_post_title: "新しい記事を作成",
        post_title_label: "タイトル",
        post_title_placeholder: "印象的なタイトルを入力してください...",
        post_summary_label: "概要 (簡潔に)",
        post_summary_placeholder: "記事の紹介文を数行入力してください...",
        post_images_label: "記事の画像 (複数選択可)",
        post_images_btn: "画像を選択",
        post_no_file: "ファイルが選択されていません",
        post_content_label: "内容",
        post_content_placeholder: "コミュニティに何を共有したいですか？",
        post_publish: "今すぐ公開",
        update_post_title: "記事を更新",
        post_images_warning: "注意：新しい画像をアップロードすると、古い画像はすべて置き換えられます。",
        post_images_btn_edit: "アップロードする新しい画像を選択",
        keep_old_images: "古い画像を保持する",
        post_id_not_found: "記事IDが見つかりません！",
        load_post_failed: "記事データの読み込みに失敗しました。",
        loaded_original_images: "{count} 枚の元の画像を読み込みました。",
        max_images_reached: "最大5枚まで選択可能です！",
        uploading_images: "{count} 枚の画像をアップロード中...",
        upload_error: "アップロードエラー",
        upload_success_count: "{count} 枚の新しい画像を選択してアップロードしました。",
        update_success: "更新が成功しました！",
        default_bio: "ここは私が考えやストーリーを共有する場所です。",
        users_section: "ユーザー",
        posts_section: "投稿",
        search_query_empty: "検索キーワードを入力してください",
        search_results_for: "の検索結果:",
        no_users_found: "ユーザーが見つかりませんでした。",
        no_posts_found: "投稿が見つかりませんでした。",
        by_author: "作成者：",
        market_suggestions: "本日のおすすめ",
        tag_shoes: "靴",
        tag_shirts: "シャツ",
        tag_bags: "バッグ",
        price_low_high: "価格の安い順",
        price_high_low: "価格の高い順",
        best_seller: "ベストセラー",
        footer_desc: "共有とショッピングのプラットフォーム。",

        // Seller Center
        open_shop_title: "Zynkでショップを開く",
        open_shop_desc: "Zynkコミュニティで今日からビジネスキャリアを始めましょう。",
        shop_name_label: "予定のショップ名",
        shop_name_placeholder: "例：Zynkモバイルストア",
        shop_desc_label: "ショップの説明",
        shop_desc_placeholder: "何を販売する予定か簡単に紹介してください...",
        submit_apply: "承認を申請する",
        pending_approval_title: "承認待ち",
        pending_approval_desc: "管理者がショップ申請を審査中です。結果が出次第、通知いたします。",
        seller_center_title: "セラーセンター",
        overview: "概要",
        products: "商品",
        orders: "注文",
        revenue_est: "推定収益",
        total_products: "総商品数",
        product_list: "商品リスト",
        add_new_product: "新商品を追加",
        th_image: "画像",
        th_name: "商品名",
        th_price: "価格",
        th_stock: "在庫",
        th_status: "ステータス",
        th_actions: "アクション",
        manage_orders: "注文管理",
        manage_orders_desc: "注文の管理と処理",
        order_search_placeholder_full: "注文ID、名前、または顧客の電話番号で検索...",
        add_product_title: "新商品を追加",
        product_name_label: "商品名",
        product_price_label: "価格 (VND)",
        product_stock_label: "在庫数",
        category_label: "カテゴリー",
        product_desc_label: "商品の説明",
        upload_image: "画像をアップロード",
        variant_config: "バリエーション設定 (オプション)",
        variant_group1_label: "グループ1の名前 (例: 色)",
        variant_group2_label: "グループ2の名前 (例: サイズ)",
        add_variant: "バリエーションを追加",
        save_and_show: "保存して公開",

        // Seller Order Detail
        back_to_seller_center: "セラーセンターに戻る",
        seller_loading_order: "出品者用の注文詳細を読み込んでいます...",
        buyer_info: "購入者情報",
        customer_name: "顧客名",
        phone_number: "電話番号",
        pack_items: "梱包する商品",
        payment_info: "お支払い情報",
        total_amount: "合計金額",
        payment_method: "支払い方法",
        order_processing: "注文処理",
        current_status: "現在のステータス:",
        order_id_label: "注文ID:",
        order_date_label: "注文日:",

        // Order Detail (Buyer)
        back_to_my_orders: "注文履歴に戻る",
        loading_order_info: "注文情報を読み込んでいます...",
        order_success: "注文完了",
        preparing_items: "商品を準備中",
        shipping_fee: "送料",
        free: "無料",
        discount: "割引",
        total_payment: "合計支払い",
        order_info_title: "注文情報",
        order_time_label: "注文時間",
        payment_method_label: "支払い方法",
        cancel_order: "注文をキャンセル",
        update_address_title: "配送先住所を更新",
        province_label: "都道府県",
        dist_ward_label: "市区町村",
        specific_address_label: "詳細な住所",

        // Cart
        total_label: "合計:",
        shipping_info_title: "配送情報",
        saved_addresses: "保存された住所",
        select_province: "都道府県を選択",
        district_label: "市区町村",
        select_district: "市区町村を選択",
        save_address_future: "次回のためにこの住所を保存する",
        order_note_optional: "注文メモ (オプション)",
        payment_method_title: "支払い方法",
        payment_cod: "代金引換 (COD)",
        payment_bank: "銀行振込 / カード",
        order_now: "今すぐ注文",
        empty_cart: "カートは空です。",
        processing: "処理中...",
        select_all: "すべて選択",

        // Admin
        admin_dashboard: "管理ダッシュボード",
        manage_users: "ユーザー管理",
        violation_reports: "違反報告",
        manage_shops: "ショップ管理",
        manage_categories: "カテゴリー管理",
        back_home: "ホームに戻る",
        users_list: "ユーザーリスト",
        reporter: "報告者",
        reported_post: "報告された投稿",
        reason: "理由",
        status: "ステータス",
        applicant: "申請者",
        shop_name: "ショップ名",
        request_date: "申請日",
        categories_desc_admin: "カテゴリーをクリックして、その中のサブアイテムを表示します",
        add_category: "カテゴリーを追加",
        category_name_label: "カテゴリー名",
        category_icon_label: "アイコン (FontAwesome class)",
        parent_category_label: "親カテゴリー",
        none_root: "-- なし (ルートカテゴリー) --",
        preview_post_title: "投稿をプレビュー",

        my_posts: "自分の投稿",
        post_now: "今すぐ投稿",

        // Marketplace & Search
        search_btn: "検索",
        categories_title: "カテゴリー",
        all: "すべて",

        // Cart & Orders
        cart_title: "ショッピングカート",
        checkout: "チェックアウト",
        total: "合計",
        status_all: "すべて",
        status_pending: "保留中",
        status_delivering: "配送中",
        status_completed: "完了",
        status_cancelled: "キャンセル",
        admin_dashboard: "管理者ダッシュボード",
        manage_users: "ユーザー管理",
        manage_posts: "投稿管理",
        manage_shops: "ショップ管理",
        system_stats: "システム統計",
        total_users: "総ユーザー数",
        total_posts: "総投稿数",
        total_orders: "総注文数",
        total_revenue: "総収益",
        violation_reports: "違反報告",
        manage_categories: "カテゴリー管理",
        back_home: "ホームへ戻る",
        users_list: "ユーザーリスト",
        refresh: "更新",
        reporter: "報告者",
        reported_post: "報告された投稿",
        reason: "理由",
        applicant: "申請者",
        shop_name: "ショップ名",
        description: "説明",
        request_date: "申請日",
        joined_label: "参加日",
        actions_label: "アクション",
        email_label: "メール",
        role_label: "役割"
    }
};
