// js/lang.js - Dictionary for Zynk i18n system

window.zynkTranslations = {
    vi: {
        // Common
        app_name: "Zynk",
        home: "Trang chủ",
        marketplace: "Chợ Zynk",
        seller_center: "Kênh Người Bán",
        my_orders: "Đơn mua",
        settings: "Cài đặt",
        profile: "Hồ sơ cá nhân",
        admin_panel: "Quản trị",
        logout: "Đăng xuất",
        login: "Đăng nhập",
        register: "Đăng ký",
        search_placeholder: "Tìm kiếm bài viết, người dùng...",
        loading: "Đang tải...",
        save_changes: "Lưu thay đổi",
        cancel: "Hủy",
        delete: "Xóa",
        user: "Người dùng",
        error: "Lỗi",
        
        // Header/Nav
        greeting: "Chào, ",
        notifications: "Thông báo",
        mark_all_read: "Đánh dấu tất cả đã đọc",
        no_notifications: "Không có thông báo mới",
        shopping: "Mua sắm",
        post_new: "Đăng bài mới",
        
        // Home Page
        news_feed: "Bảng tin",
        latest: "Mới nhất",
        following: "Đang theo dõi",
        no_posts: "Mọi thứ thật yên tĩnh. Hãy là người đầu tiên đăng bài!",
        quick_post_placeholder: "Bạn đang nghĩ gì thế?",
        
        // Settings Page
        settings_title: "Cài đặt tài khoản",
        settings_desc: "Quản lý thông tin cá nhân và trải nghiệm của bạn.",
        tab_profile: "Hồ sơ cá nhân",
        tab_account: "Bảo mật",
        tab_privacy: "Quyền riêng tư",
        tab_notifications: "Thông báo",
        tab_marketplace: "Bán hàng",
        tab_interface: "Giao diện",
        tab_language: "Ngôn ngữ",
        tab_danger: "Vùng nguy hiểm",
        
        // Language Section
        lang_section_title: "Ngôn ngữ hệ thống",
        lang_section_desc: "Chọn ngôn ngữ hiển thị bạn mong muốn.",
        select_lang: "Chọn ngôn ngữ",
        lang_vi: "Tiếng Việt",
        lang_en: "Tiếng Anh (English)",
        lang_ja: "Tiếng Nhật (日本語)",
        lang_applied: "Đã cập nhật ngôn ngữ!",
        
        // Profile Page
        posts_label: "Bài viết",
        followers_label: "Người theo dõi",
        following_label: "Đang theo dõi",
        follow: "Theo dõi",
        unfollow: "Hủy theo dõi",
        my_posts: "Bài đăng của tôi",
        no_posts_user: "Bạn chưa có bài đăng nào.",
        post_now: "Đăng bài ngay",
        user_timeline: "Dòng thời gian",
        
        // Marketplace & Search
        search_btn: "Tìm",
        market_search_placeholder: "Tìm kiếm sản phẩm, cửa hàng...",
        categories_title: "Danh mục",
        all: "Tất cả",
        add_to_cart: "Thêm vào giỏ",
        buy_now: "Mua ngay",
        
        // Cart & Orders
        cart_title: "Giỏ hàng của bạn",
        checkout: "Thanh toán",
        subtotal: "Tạm tính",
        total: "Tổng cộng",
        empty_cart: "Giỏ hàng trống",
        order_status: "Trạng thái đơn hàng",
        status_all: "Tất cả",
        status_pending: "Chờ xác nhận",
        status_unpaid: "Chưa thanh toán",
        status_awaiting: "Chờ giao hàng",
        status_delivering: "Đang giao",
        status_delivered: "Đã giao hàng",
        status_completed: "Hoàn thành",
        status_cancelled: "Đã hủy",
        orders_desc: "Theo dõi và quản lý lịch sử mua sắm của bạn",
        find_order: "Tìm đơn hàng",
        order_search_placeholder: "Tìm theo Mã đơn hoặc Tên sản phẩm...",
        searching: "Đang tìm kiếm...",
        users_section: "Người dùng",
        posts_section: "Bài viết",
        
        // Order Details
        order_detail_title: "Chi tiết đơn hàng - Zynk",
        back_to_orders: "Quay lại đơn hàng mang tôi",
        shipping_address: "Địa chỉ nhận hàng",
        items_list: "Danh sách sản phẩm",
        order_summary: "Tổng kết đơn hàng",
        step_unpaid: "Chờ thanh toán",
        step_pending: "Chờ xác nhận",
        step_awaiting: "Chờ giao hàng",
        step_delivering: "Đang giao",
        step_completed: "Hoàn thành",
        payment_info_title: "Thanh toán",
        shipping_fee: "Phí vận chuyển",
        free: "Miễn phí",
        discount: "Giảm giá",
        total_payment: "Tổng thanh toán",
        order_info_title: "Thông tin đơn hàng",
        order_id_label: "Mã đơn hàng",
        order_time_label: "Thời gian đặt",
        payment_method_label: "Phương thức",
        
        // Seller Center Details
        seller_order_detail_title: "Chi tiết đơn hàng - Kênh Người Bán",
        back_to_seller_center: "Quay lại Kênh người bán",
        seller_loading_order: "Đang tải chi tiết đơn hàng cho người bán...",
        buyer_info: "Thông tin người mua",
        customer_name: "Tên khách hàng",
        phone_number: "Số điện thoại",
        pack_items: "Sản phẩm cần đóng gói",
        processing: "Xử lý đơn hàng",
        current_status: "Trạng thái hiện tại",
        auth_title: "Xác thực - Zynk",
        auth_welcome: "Chào mừng trở lại!",
        auth_slogan: "Nền tảng mạng xã hội kết nối, chia sẻ kiến thức số 1.",
        
        // Post Creation/Editing
        create_post_title: "Tạo bài viết mới",
        edit_post_title: "Chỉnh sửa bài viết",
        post_title_label: "Tiêu đề",
        post_title_placeholder: "Nhập tiêu đề ấn tượng...",
        post_summary_label: "Tóm tắt (Ngắn gọn)",
        post_summary_placeholder: "Một vài dòng giới thiệu về bài viết...",
        post_images_label: "Hình ảnh bài viết",
        post_images_btn: "Chọn ảnh bài viết",
        post_no_file: "Chưa có ảnh nào được chọn",
        post_content_label: "Nội dung bài viết",
        post_publish: "Đăng bài viết ngay",
        update_post_title: "Cập nhật bài viết",
        post_images_warning: "Lưu ý: Nếu bạn tải lên hình ảnh mới, toàn bộ hình ảnh cũ sẽ bị thay thế.",
        keep_old_images: "Giữ nguyên ảnh cũ",
        post_images_btn_edit: "Chọn ảnh mới tải lên",
        
        // Admin
        admin_dashboard: "Bảng điều khiển quản trị",
        manage_users: "Quản lý người dùng",
        manage_posts: "Quản lý bài viết",
        manage_shops: "Quản lý cửa hàng",
        system_stats: "Thống kê hệ thống",
        total_users: "Tổng người dùng",
        total_posts: "Tổng bài viết",
        total_orders: "Tổng đơn hàng",
        total_revenue: "Doanh thu hệ thống",
        violation_reports: "Báo cáo vi phạm",
        manage_categories: "Quản lý Danh mục",
        back_home: "Quay lại Home",
        users_list: "Danh sách người dùng",
        refresh: "Làm mới",
        
        // Footer
        footer_copy: "&copy; 2026 Zynk Community. Made with LV for developers."
    },
    en: {
        // Common
        app_name: "Zynk",
        home: "Home",
        marketplace: "Zynk Market",
        seller_center: "Seller Center",
        my_orders: "My Orders",
        settings: "Settings",
        profile: "Profile",
        admin_panel: "Admin",
        logout: "Logout",
        login: "Login",
        register: "Register",
        search_placeholder: "Search posts, users...",
        loading: "Loading...",
        save_changes: "Save Changes",
        cancel: "Cancel",
        delete: "Delete",
        user: "User",
        error: "Error",
        
        // Header/Nav
        greeting: "Hi, ",
        notifications: "Notifications",
        mark_all_read: "Mark all as read",
        no_notifications: "No new notifications",
        shopping: "Shopping",
        post_new: "Post New",
        
        // Home Page
        news_feed: "News Feed",
        latest: "Latest",
        following: "Following",
        no_posts: "Everything is quiet. Be the first to post!",
        quick_post_placeholder: "What's on your mind?",
        
        // Settings Page
        settings_title: "Account Settings",
        settings_desc: "Manage your personal information and experience.",
        tab_profile: "Profile",
        tab_account: "Security",
        tab_privacy: "Privacy",
        tab_notifications: "Notifications",
        tab_marketplace: "Marketplace",
        tab_interface: "Appearance",
        tab_language: "Language",
        tab_danger: "Danger Zone",
        
        // Language Section
        lang_section_title: "System Language",
        lang_section_desc: "Choose your preferred display language.",
        select_lang: "Select Language",
        lang_vi: "Vietnamese",
        lang_en: "English",
        lang_ja: "Japanese (日本語)",
        lang_applied: "Language updated!",

        // Profile Page
        posts_label: "Posts",
        followers_label: "Followers",
        following_label: "Following",
        follow: "Follow",
        unfollow: "Unfollow",
        my_posts: "My Posts",
        no_posts_user: "You don't have any posts yet.",
        post_now: "Post now",
        user_timeline: "User Timeline",

        // Marketplace & Search
        search_btn: "Search",
        market_search_placeholder: "Search products, shops...",
        categories_title: "Categories",
        all: "All",
        add_to_cart: "Add to Cart",
        buy_now: "Buy Now",

        // Cart & Orders
        cart_title: "Your Cart",
        checkout: "Checkout",
        subtotal: "Subtotal",
        total: "Total",
        empty_cart: "Your cart is empty",
        order_status: "Order Status",
        status_all: "All",
        status_pending: "Pending",
        status_unpaid: "Unpaid",
        status_awaiting: "Awaiting Shipment",
        status_delivering: "Delivering",
        status_delivered: "Delivered",
        status_completed: "Completed",
        status_cancelled: "Cancelled",
        orders_desc: "Follow and manage your shopping history",
        find_order: "Find Order",
        order_search_placeholder: "Search by Order ID or Product name...",
        searching: "Searching...",
        users_section: "Users",
        posts_section: "Posts",

        // Order Details
        order_detail_title: "Order Detail - Zynk",
        back_to_orders: "Back to my orders",
        shipping_address: "Shipping Address",
        items_list: "Product List",
        order_summary: "Order Summary",
        step_unpaid: "Unpaid",
        step_pending: "Pending",
        step_awaiting: "Awaiting Shipment",
        step_delivering: "Delivering",
        step_completed: "Completed",
        payment_info_title: "Payment",
        shipping_fee: "Shipping Fee",
        free: "Free",
        discount: "Discount",
        total_payment: "Total Payment",
        order_info_title: "Order Information",
        order_id_label: "Order ID",
        order_time_label: "Order Time",
        payment_method_label: "Method",
        
        // Seller Center Details
        seller_order_detail_title: "Order Detail - Seller Center",
        back_to_seller_center: "Back to Seller Center",
        seller_loading_order: "Loading order details for seller...",
        buyer_info: "Buyer Information",
        customer_name: "Customer Name",
        phone_number: "Phone Number",
        pack_items: "Items to Pack",
        processing: "Processing",
        current_status: "Current Status",
        auth_title: "Auth - Zynk",
        auth_welcome: "Welcome Back!",
        auth_slogan: "Top social platform for knowledge sharing.",

        // Post Creation/Editing
        create_post_title: "Create New Post",
        edit_post_title: "Edit Post",
        post_title_label: "Title",
        post_title_placeholder: "Enter an impressive title...",
        post_summary_label: "Summary (Brief)",
        post_summary_placeholder: "A few lines of introduction...",
        post_images_label: "Post Images",
        post_images_btn: "Select images",
        post_no_file: "No images selected",
        post_content_label: "Post Content",
        post_publish: "Publish Post Now",
        update_post_title: "Update Post",
        post_images_warning: "Note: If you upload new images, all old ones will be replaced.",
        keep_old_images: "Keep old images",
        post_images_btn_edit: "Select new images to upload",

        // Admin
        admin_dashboard: "Admin Dashboard",
        manage_users: "Manage Users",
        manage_posts: "Manage Posts",
        manage_shops: "Manage Shops",
        system_stats: "System Statistics",
        total_users: "Total Users",
        total_posts: "Total Posts",
        total_orders: "Total Orders",
        total_revenue: "System Revenue",
        violation_reports: "Violation Reports",
        manage_categories: "Manage Categories",
        back_home: "Back to Home",
        users_list: "Users List",
        refresh: "Refresh",

        // Admin
        admin_dashboard: "Admin Dashboard",
        manage_users: "Manage Users",
        manage_posts: "Manage Posts",
        manage_shops: "Manage Shops",
        system_stats: "System Statistics",
        total_users: "Total Users",
        total_posts: "Total Posts",
        total_orders: "Total Orders",
        total_revenue: "System Revenue",
        
        // Footer
        footer_copy: "&copy; 2026 Zynk Community. Made with LV for developers."
    },
    ja: {
        // Common (Japanese)
        app_name: "Zynk",
        home: "ホーム",
        marketplace: "マーケット",
        seller_center: "セラーセンター",
        my_orders: "購入注文",
        settings: "設定",
        profile: "プロファイル",
        admin_panel: "管理",
        logout: "ログアウト",
        login: "ログイン",
        register: "登録",
        search_placeholder: "検索する...",
        loading: "読み込み中...",
        save_changes: "保存する",
        cancel: "キャンセル",
        delete: "削除",
        user: "ユーザー",
        error: "エラー",
        
        // Header/Nav
        greeting: "こんにちは、",
        notifications: "通知",
        mark_all_read: "すべて既読にする",
        no_notifications: "通知はありません",
        shopping: "ショッピング",
        post_new: "投稿する",
        
        // Home Page
        news_feed: "フィード",
        latest: "最新",
        following: "フォロー中",
        no_posts: "まだ投稿がありません。",
        quick_post_placeholder: "何を考えていますか？",
        
        // Language Section
        lang_section_title: "システム言語",
        lang_section_desc: "表示言語を選択してください。",
        select_lang: "言語を選択",
        lang_vi: "ベトナム語",
        lang_en: "英語",
        lang_ja: "日本語",
        lang_applied: "言語を更新しました！",

        // Profile Page
        posts_label: "投稿",
        followers_label: "フォロワー",
        following_label: "フォロー中",
        follow: "フォロー",
        unfollow: "フォロー解除",
        my_posts: "自分の投稿",
        post_now: "今すぐ投稿",

        // Marketplace & Search
        search_btn: "検索",
        categories_title: "カテゴリー",
        all: "すべて",

        // Cart & Orders
        cart_title: "ショッピングカート",
        checkout: "チェックアウト",
        total: "合計",
        status_all: "すべて",
        status_pending: "保留中",
        status_delivering: "配送中",
        status_completed: "完了",
        status_cancelled: "キャンセル",
        admin_dashboard: "管理者ダッシュボード",
        manage_users: "ユーザー管理",
        manage_posts: "投稿管理",
        manage_shops: "ショップ管理",
        system_stats: "システム統計",
        total_users: "総ユーザー数",
        total_posts: "総投稿数",
        total_orders: "総注文数",
        total_revenue: "総収益",
        violation_reports: "違反報告",
        manage_categories: "カテゴリー管理",
        back_home: "ホームへ戻る",
        users_list: "ユーザーリスト",
        refresh: "更新",
        reporter: "報告者",
        reported_post: "報告された投稿",
        reason: "理由",
        applicant: "申請者",
        shop_name: "ショップ名",
        description: "説明",
        request_date: "申請日",
        joined_label: "参加日",
        actions_label: "アクション",
        email_label: "メール",
        role_label: "役割"
    }
};
